services:
  - type: web
    name: mrsd-backend
    runtime: docker
    repo: https://github.com/sri-nikesh-1432/Mrs.D-DoneswariTech.git
    plan: free
    dockerfilePath: ./backend/Dockerfile
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: ALLOWED_ORIGINS
        value: '["https://dtechp1.netlify.app"]'
      - key: DATABASE_URL
        value: sqlite+aiosqlite:////app/mrsd_campaign.db